services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped

    environment:
      USER_UID: 1000
      USER_GID: 1000

    volumes:
      - ./data:/data

    ports:
      - "3002:3000"
      - "2222:22"

    networks:
      - homelab

networks:
  homelab:
    external: true
