- Infrastructure:
    - Portainer:
        icon: portainer.png
        href: https://homeserver.taild3ee76.ts.net:9443
        siteMonitor: http://portainer:9000

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://homeserver.taild3ee76.ts.net:3001
        siteMonitor: http://uptime-kuma:3001

- Storage:
    - Nextcloud:
        icon: nextcloud.png
        href: http://homeserver.taild3ee76.ts.net:8080
        siteMonitor: http://nextcloud
- Development:
    - Gitea:
        href: http://homeserver.taild3ee76.ts.net:3002
        icon: gitea.png

- AI:
    - Jarvis:
        href: http://homeserver.taild3ee76.ts.net:8001
        icon: mdi-robot
        description: Personal AI Assistant

- Photos:
    - Immich:
        href: http://homeserver.taild3ee76.ts.net:2283
        icon: immich
        description: Self-hosted Google Photos

- System:
    - Edith Battery:
        icon: mdi-battery
        description: Laptop Battery
        widget:
          type: customapi
          url: http://172.20.0.1:9000
          refreshInterval: 10000
          mappings:
            - field: battery
              label: Battery
              format: number
            - field: status
              label: Status
